# Generated by Django 3.1.2 on 2020-11-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ip',
            fields=[
                ('ipaddress', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('date_last_try', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nameproduct', models.CharField(max_length=100)),
                ('descripction', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('is_active', models.BooleanField(auto_created=True, default=False)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField()),
                ('date_auth', models.DateTimeField()),
                ('token', models.CharField(max_length=60)),
            ],
        ),
    ]
