# Generated by Django 3.1.2 on 2020-11-07 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_users_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip',
            old_name='ipaddress',
            new_name='ip_address',
        ),
    ]
