# Generated by Django 3.1.3 on 2020-11-17 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nameproduct', models.CharField(max_length=100)),
                ('descripction', models.TextField(max_length=500)),
                ('price', models.FloatField(max_length=10)),
                ('discount', models.FloatField(default=0, max_length=10)),
                ('id_user', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.category')),
            ],
        ),
    ]
