"""
Django settings for firstapi project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
JsonResponses://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
JsonResponses://docs.djangoproject.com/en/3.1/ref/settings/
"""
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See JsonResponses://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p9t4=##5jroyswe4d9pln@=fsfu26w#%_uw=j7enl&vo7&t4yi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.authtoken',
    'app',
    'produto',
    'pedidos',
    'app.others',
    'rest_framework',
    'djangosecure',
    'sslserver',
]

MIDDLEWARE = [
    'djangosecure.middleware.SecurityMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'firstapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'firstapi.wsgi.application'

SECURE_SSL_REDIRECT = True
# Database
# JsonResponses://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'apirest',
        'USER': 'dolfim',
        'PASSWORD':'dolfimdolfim',
        'HOST': '',
        'PORT': '3305',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset':'utf8'
        }
    }
}


# Password validation
# JsonResponses://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# JsonResponses://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

DATETIME_FORMAT = "%d-%m-%Y%H:%M:%S"

TIME_ZONE = 'America/Sao_Paulo'

DEFAULT_CHARSET='utf-8'

USE_I18N = True

USE_L10N = False

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# JsonResponses://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

#LOGIN_REDIRECT_URL='/'

EMAIL_HOST=config('EMAIL_HOST')
EMAIL_HOST_USER=config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD=config('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS=config('EMAIL_USE_TLS')
EMAIL_PORT=config('EMAIL_PORT')
DEFAULT_FROM_EMAIL=config('EMAIL_HOST_USER')
RECAPTCHA_PRIVATE_KEY=config('RECAPTCHA_PRIVATE_KEY')
KEY = config('KEY')